config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :questions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
    validates :title, presence: true
    validates :name, presence: true
    validates :content, presence: true, length: { minimum: 5 }
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to @question
    else
      render "new", status: :unprocessable_entity
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      redirect_to @question
    else
      render "edit", status: :unprocessable_entity
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to questions_path
  end

  private

  def question_params
    params.require(:question).permit(:title, :name, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qanda</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_with(model: @question) do |form| %>
    <% if @question.errors.any? %>
      <div>
        <ul>
          <% @question.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

<div>
<%= form.label :title%><br>
<%= form.text_field :title%>
</div>

<div>
<%= form.label :name%><br>
<%= form.text_field :name%>
</div>
<div>
<%= form.label :content%><br>
<%= form.text_field :content%>
</div>
<div><%=form.submit%></div>


<%end%>

app/views/questions/edit.html.erb
<h1>edit</h1>

<%= render partial: 'form' %>

app/views/questions/index.html.erb
<h1>hello</h1>

<%= link_to 'new', new_question_path %>

<table>
  <tr>
    <th>ID</th>
    <th>Title</th>
    <th>Name</th>
    <th>Content</th>
    <th></th>
  </tr>

    <% @questions.each do |question| %>
    <tr>
      <td><%= question.id %></td>
      <td><%= question.title %></td>
      <td><%= question.name %></td>
      <td><%= question.content %></td>
      <td><%= link_to "Show", question_path(question) %></td>
      <td><%= link_to "edit", edit_question_path(question) %></td>
      <td><%= link_to "Destroy", question_path(question),
                    data: { turbo_method: 'delete', turbo_confirm: ' Are you Sure ?'} %></td>
    </tr>
  <% end %>
</table>

app/views/questions/new.html.erb
<h1> Questions </h1>

<%= render partial: 'form' %>

app/views/questions/show.html.erb
<h1>show</h1>
<p>
Title :<br>
  <%= @question.title %>
</p>

<p>
Name :<br>
  <%= @question.name %>
</p>

<p>
Content :<br>
  <%= @question.content %>
</p>

<%= link_to 'top', questions_path %>